apiVersion: v1
kind: Pod
metadata:
  name: jmxmonitor
spec:
  containers:
    - name: tomcat
      image: tomcat:9-jre11
      env:
        - name: CATALINA_OPTS
          value: "-Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false"
      ports:
        - containerPort: 8080
        - containerPort: 9010
    - name: reporter
      image: testreporter:0.0.1-SNAPSHOT